# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distance <- function(dem, center, res) {
    .Call(`_enerscape_distance`, dem, center, res)
}

energy <- function(slope, distance, mass, res, kcal = TRUE) {
    .Call(`_enerscape_energy`, slope, distance, mass, res, kcal)
}

energyscape <- function(m, n = 4L, mass = 0, res = 0, kcal = TRUE) {
    .Call(`_enerscape_energyscape`, m, n, mass, res, kcal)
}

neighbours <- function(i, j, n, m) {
    .Call(`_enerscape_neighbours`, i, j, n, m)
}

slope <- function(dem, center, res) {
    .Call(`_enerscape_slope`, dem, center, res)
}

